
addpath('./img/BioTracs/');
addpath('../tests/')
autoload( ...
    'PkgPaths', {fullfile(pwd, '../../')}, ...
    'Dependencies', {...
        'biotracs-m-mimosa', ...
        'biotracs-m-lipidmatch', ...
    }, ...
    'Variables',  struct(...
    'OpenMSBinPath', 'C:/Program Files/OpenMS-2.4.0/bin/', ...
    'MzConvertFilePath', 'C:\Program Files\ProteoWizard\ProteoWizard 3.0.9992\msconvert.exe', ...
    'RExecutableFilePath', 'C:/Program Files/R/R-3.3.3/bin/Rscript.exe', ...
    'LipidMatchFilePath', '%BIOTRACS_M_LIPIDMATCH_DIR%/externs/r/LipidMatch/v2/LipidMatch_v4.r', ...
    'LipidMatchLibraryPath', '%BIOTRACS_M_LIPIDMATCH_DIR%/externs/r/LipidMatch/v2/LipidMatch_Libraries_acetate' ...
    ) ...
);

popup_App;